models:
  led:
    batch_size: 1
    device: auto  # Auto-détection: MPS pour M1, CUDA pour GPU NVIDIA, CPU sinon
    generation_config:
      do_sample: false
      early_stopping: true
      length_penalty: 2.0        # Plus pénalisant pour éviter les textes trop longs
      max_length: 512
      min_length: 80             # Minimum plus élevé pour forcer du contenu
      no_repeat_ngram_size: 4    # Plus strict contre les répétitions
      num_beams: 4               # Plus de beams pour plus de qualité
      repetition_penalty: 1.3    # Plus pénalisant pour les répétitions
      temperature: 1.0
    max_input_length: 4096
    max_output_length: 512
    model_name: allenai/led-base-16384
  ner:
    entities:
    - PERSON
    - ORG
    - GPE
    - DATE
    - MONEY
    model_name: fr_core_news_sm
  openai:
    fallback_model: gpt-3.5-turbo
    max_tokens: 500
    model_name: gpt-4
    temperature: 0.3
summary_lengths:
  long:
    max_length: 500
    min_length: 200
    target_length: 350
  short:
    max_length: 150
    min_length: 50
    target_length: 100
training:
  eval_steps: 500
  fp16: true
  gradient_accumulation_steps: 4
  learning_rate: 5e-5
  logging_steps: 250
  num_epochs: 3
  save_steps: 500
  save_total_limit: 2
  warmup_steps: 500
  weight_decay: 0.01
